version: '3'

services:
  apppostgres:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: apppostgres-docker
    container_name: apppostgres
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET : ${JWT_SECRET}
      JWT_EXPIRES_IN : ${JWT_EXPIRES_IN}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
